kind: pipeline
name: github

steps:
- name: check for accidentally dropped creds
  image: yellowmegaman/container-trufflehog:2.0.98
  commands:
  - /usr/local/bin/trufflehog --regex --entropy=False file:///$CI_WORKSPACE

- name: pack
  image: yellowmegaman/container-packer:1.3.3
  environment:
    DOCKER_HOST: tcp://serviced:2375
    FROM_IMAGE: "python:3.7.1-alpine3.8"
    YAMLLINT_VERSION: 1.13.0
    PROJECT_NAME: yellowmegaman
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    QUAY_USERNAME:
      from_secret: quay_username
    QUAY_PASSWORD:
      from_secret: quay_password
  commands:
  - packer build "$DRONE_REPO_NAME".json

services:
- name: serviced
  image: plugins/docker
  entrypoint: [ dockerd ]
  command: [ '-H', 'tcp://0.0.0.0:2375', '--iptables=false' ]
