name: container
on:
  push:
  schedule:
  - cron:  '35 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v1
    - name: the-more-you-know
      run: env | sort
    - name: packer action
      uses: yellowmegaman/github-action-get-packer@0.0.1
      with:
        args: ["build", "container-yamllint.json"]
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        YAMLLINT_VERSION: 1.17.0
        PROJECT_NAME: yellowmegaman
        FROM_IMAGE: python:3.7.4-alpine
